name: Test
on: [push, pull_request]
jobs:

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        go:
          - '1.8'
          - '1.9'
          - '1.10'
          - '1.11'
          - '1.12'
          - '1.13'

    steps:

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go
      - run: |
          go version
          echo ::set-env name=GOPATH::$GITHUB_WORKSPACE
        shell: bash

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: src/github.com/shogo82148/go-sql-proxy

      - name: Test
        run: go test -v -coverprofile=coverage.txt .
        env:
          GO111MODULE: "on"
        shell: bash
        working-directory: src/github.com/shogo82148/go-sql-proxy

      - name: Send coverage to coveralls.io
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.txt
          parallel: true
          working-directory: src/github.com/shogo82148/go-sql-proxy
      - name: Send coverage to codecov.io
        run: bash <(curl -s https://codecov.io/bash)
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        working-directory: src/github.com/shogo82148/go-sql-proxy
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: finish
        uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
