name: Go
on: [push, pull_request]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
        - '1.11'
        - '1.12'
        - '1.13'

    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: go test -v -coverprofile=profile.cov .
      env:
        GO111MODULE: "on"

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        GO111MODULE=off go get github.com/shogo82148/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -parallel -jobid=$GITHUB_SHA -service=github

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: finish
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: curl -sS "https://coveralls.io/webhook" -d "repo_token=$COVERALLS_TOKEN&repo_name=$GITHUB_REPOSITORY&payload[build_num]=$GITHUB_SHA&payload[status]=done"
